spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_board
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
       client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}


  sql:
    init:
      mode: always

  jwt:
    secret-key: Mbma4t+JSaMvOmuQqSvME+5Vq0ofLu1F+y4dI+zPriY=
    expiration: 3600000

server:
 port: 8080


